areas:
  - base: C:\Users\bcuff\src
    base_source: with-buddies-server\WithBuddies.Web.Admin.Core
    base_dest: Dice-Server\Dice.Web.Admin
    policies:
    - source: Scripts\
      dest: Scripts\CoreScripts\
      filter: '*.js'
      recursive: true
    - source: Content\
      dest: Content\CoreContent\
      filter: '*.js'
      recursive: true
    - source: Content\
      dest: Content\CoreContent\
      filter: '*.less'
      recursive: true
    - source: Content\
      dest: Content\CoreContent\
      filter: '*.css'
      recursive: true
    - source: Views\
      dest: Views\CoreViews\
      filter: '*.cshtml'
      recursive: true
